"""empty message

Revision ID: 4068dd709f05
Revises: 08dab3f74f8c
Create Date: 2024-05-01 00:30:29.575655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4068dd709f05'
down_revision: Union[str, None] = '08dab3f74f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sugarlevels', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sugarlevels', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sugarlevels', type_='foreignkey')
    op.drop_column('sugarlevels', 'owner_id')
    # ### end Alembic commands ###
